### ISSUE TITLE
Rive file with images do not work in JS runtime

### ISSUE THREAD

**Issue by julianschmuckli** [rive-app/rive-wasm#166]
Hello,

I currently have a problem with a Rive implementation for a website. I try to implement the following Rive Animation, which I have published [here](https://rive.app/community/1782-3522-beamer/) in to the website. As you can see, there are two embedded images and this works well on the community page. Now when I try to do the same on a Nuxt.js page it does not work unfortunately.

I have here a Codepen, which demonstrates the case: https://codepen.io/julianschmuckli/pen/rNGJGjg?editors=1000

This is an example from the quick start guide. I just replaced the URL from `https://cdn.rive.app/animations/off_road_car_v7.riv` to `https://public.rive.app/community/runtime-files/1782-3522-beamer.riv`.

The error received from the library is the following:
![image](https://user-images.githubusercontent.com/6286544/147708020-eb78fbb6-0114-4efc-b0b3-981bf301d611.png)

And I use the latest runtime version with is 0.7.33.

 
Thanks for your help.

**Comment by zplata** [comment]
Hi @julianschmuckli! The NPM packages for the web runtime were updated very recently to split `rive-js` into separate packages, and with this change comes the support for raster assets. We're working to update this across our docs site as well shortly here. 

Check out the latest on the new packages [here](https://github.com/rive-app/rive-wasm#installing). Instead of importing via `rive-js`, you can use for example:
```
import rive from '@rive-app/webgl'
```
 I was able to use your public riv file and get it to render in a small CodeSandbox example. You can check it out here: https://codesandbox.io/s/rive-plainjs-repro-discord-1-8xc1h?file=/src/index.js

Hopefully this helps!

**Comment by julianschmuckli** [comment]
Hi @zplata,

thank you for your answer. Yes it does not work for me as well. But I have now installed the Canvas version (`@rive-app/canvas`) which does work as well, and may has a bit better quality in my opinion. 

Thanks.
