### ISSUE TITLE
WASM file size and lighter rive engine 

### ISSUE THREAD

**Issue by flavienbonvin** [rive-app/rive-wasm#285]
Hi,

preloading the wasm file is great since it allow getting everything setup before users see animations. However, the file size is quite large and can have an impact on infrastructure (the file is 196 KB). 

It would be great to see some size trimming on the wasm file to speed loading and reduce impact on infra. It could also be great to have a `rive-lite.wasm` engine that have a reduce set of features (state machines for examples) to avoid loading the whole file but a smaller one with less feature. 

Is there some plan to reduce the file size or offer a slimmer version?

**Comment by zplata** [comment]
Hi @flavienbonvin ! The WASM file that gets built is already optimized for small size (especially using the canvas variant), but the bulk of the size comes from the bindings to JS from CPP (you can see in `wasm/src/bindings.cpp` most of the bindings to JS classes/methods/properties). We try to keep bindings down to a minimum and as-needed basis. Because a "lite" version would be hard to predict for a general user's needs, it'd be tricky to come up with an even lighter version for a WASM build.

However, what you can experiment with is forking this repo, and removing bindings you don't need for your own project. For example:
- If you don't use LinearAnimations (you just use State Machines), you can remove the [LinearAnimation](https://github.com/rive-app/rive-wasm/blob/master/wasm/src/bindings.cpp#L366) binding
- If you don't use the low-level runtimes or you don't need to track certain nodes in the Rive draw hierarchy, or bones, you can remove the [Node](https://github.com/rive-app/rive-wasm/blob/master/wasm/src/bindings.cpp#L327) and [Bone](https://github.com/rive-app/rive-wasm/blob/master/wasm/src/bindings.cpp#L335) (and RootBone) classes
- If you reference state machines by name only (and not index), you can remove this [function binding](https://github.com/rive-app/rive-wasm/blob/master/wasm/src/bindings.cpp#L284)

It might shave off some kB to help lessen the impact
